language: cpp
compiler: gcc
dist: bionic
services:
        - xvfb

addons:
        sonarcloud:
                organization: "squinky86"
                token:
                        secure: "VYE/Qo6UjT6ULSUYB//ze/T1tsop9QROIPxYCxl1C7/8AHzDFyq7LF4OrUygel8MEXwoH8IaCl2I5t31qhnwKLBV0o75yVRX7Mntp1rGAEiK+TfJzuBo5Tc1Bbft6yvh/92jEOZmLwXOcnmZLV62KRZCASQZbZvkYuw3jWzeWBuSpq5HtxHPWcu+uEBoxKHotklx7g2lXsBeXn+tpmMZiGyk4HceOvYg95bWxlSvrkZxAIBexi/TVGC5KJ+dxj9AJt29kyAsV5+778Phyb+0N6ga+I+uN2PhaxXLkWuQgFbgTBMOuc6INF+nEwFmyIaGVDv8mRuRGLiMowXhHCy1YE4N5sKO1izaiEiAjB+5XkGrEsHvj9Q9QeLGansWVEGxAsGhpdF/Kh58phciTbD+FwsGdV/BuZKCO5gOpXodkhj/tjGYW6QwCeHcXfVxahZvB29MGue7JOUdkYYFfbPPbTV0mdSOAC+ZgtEeiXGAMM4YE2ZrxKJzpPE4hPYYLEsLtxF9RdGkv7ZlcweWvkUuPp9obgdq6hyI/jE4wgYCaeNQSXeTIORBKZh0ltgByWK7zE8NE+EcscvVEeMmmUgfsXK2JPnBrLCyttCOFJLLWU6+21/OYx5QWwXaOz8zt3JgpeWiLht4g62dA5MD5s/1EgTYT6PSVKNLAp/VxjMRbYQ="

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qt5-qmake qt5-default libqt5sql5-sqlite
 - sudo apt-get install libtidy-dev libzip-dev zlib1g-dev
 - sudo apt-get install texlive-luatex texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-extra-links texlive-bibtex-extra biber
 - sudo apt-get install libdevel-cover-perl
 - pushd /tmp && wget https://github.com/jmcnamara/libxlsxwriter/archive/RELEASE_1.0.0.tar.gz && tar -zxf RELEASE_1.0.0.tar.gz && popd
 - pushd /tmp/libxlsxwriter-RELEASE_1.0.0 && make && sudo make install PREFIX=/usr && popd
 - pip install --user cpp-coveralls
 - cpanm --sudo --quiet --notest Devel::Cover::Report::Kritika

script:
 - for x in `find /home/travis/.sonar/cache -name "libinterceptor-x86_64.so"`; do cp ${x} ${x/x86_64/haswell}; done
 - echo "DEFINES += USE_TESTS" >> STIGQter.pro
 - qmake STIGQter.pro
 - sed -i -e 's:-O2:-O0 -fprofile-arcs -ftest-coverage -fno-exceptions -fno-inline:g' -e 's:-Wl,-O1:-Wl,-O1 -lgcov --coverage:g' Makefile
 - build-wrapper-linux-x86-64 --out-dir bw-output make --quiet -j3
 - pushd doc && ./build.sh && popd
 - ./STIGQter tests > STIGQter.tests &
 - while [ ! -z "`pgrep STIGQter`" ]; do sleep 10 && tail -n 1 STIGQter.tests; done
 - tail -n 100 STIGQter.tests

after_success:
 - for x in src/*.cpp; do LC_ALL=en gcov --branch-probabilities --branch-counts ${x} -o .; done
 - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
 - coveralls --gcov-options '\-lp'
 - gcov2perl *.gcov >> STIGQter.tests
 - tail -n 100 STIGQter.tests
 - cover -ignore_re=^/ -ignore_re=^t -report kritika >> STIGQter.tests
 - tail -n 100 STIGQter.tests
 - bash <(curl -s https://codecov.io/bash) >> STIGQter.tests
 - tail -n 100 STIGQter.tests
