/*
 * STIGQter - STIG fun with Qt
 *
 * Copyright © 2018–2023 Jon Hood, http://www.hoodsecurity.com/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "workercciadd.h"
#include "common.h"
#include "cci.h"
#include "dbmanager.h"

#include <iostream>

#include <QDir>
#include <QDirIterator>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QTemporaryFile>
#include <QXmlStreamReader>

/**
 * @class WorkerCCIAdd
 * @brief Indexing @a CCI and @a Control information from the
 * internet can take a while. These tasks are sent to a background
 * worker process to afford progress to the user.
 *
 * This class indexes @a Family and @a Control information from NIST,
 * and it indexes @a CCI information from DISA.
 */

/**
 * @brief WorkerCCIAdd::WorkerCCIAdd
 * @param parent
 *
 * Default constructor.
 */
WorkerCCIAdd::WorkerCCIAdd(QObject *parent) : Worker(parent)
{
}

/**
 * @brief WorkerCCIAdd::CheckFamily
 * @param acronym
 * @param addedFamilies
 * @param resetDelay
 *
 * Verifies that families have been added to the database
 */
void WorkerCCIAdd::CheckFamily(const QString &acronym, const QString &description, QList<QString> &addedFamilies, bool resetDelay)
{
    if (addedFamilies.contains(acronym))
        return;

    DbManager db;
    if (resetDelay)
        db.DelayCommit(false);

    db.AddFamily(acronym, description);
    addedFamilies.append(acronym);

    if (resetDelay)
        db.DelayCommit(true);
}

/**
 * @brief WorkerCCIAdd::process
 *
 * In general:
 * @list
 * @li Download and parse the NIST RMF information.
 * @li Download and parse the cyber.mil CCI information.
 * @endlist
 */
void WorkerCCIAdd::process()
{
    Worker::process();

    //open database in this thread
    Q_EMIT initialize(1, 0);
    DbManager db;

    //populate CCIs

    //Step 1: download NIST Families and controls
    Q_EMIT updateStatus(QStringLiteral("Downloading Families and Controls…"));

    //Step 2: read the families and controls
    //Families and controls are read from the bundled NIST 800-53 Rev 5 catalog
    //(src/800-53-rev5-controls.xml, generated by scripts/generate_rev5_controls.py).
    //Unlike Rev 4, privacy controls are integrated into the main catalog (e.g. the
    //PT family), so no families or Appendix J controls are hardcoded here.
    QList<QString> familiesAdded;
    Q_EMIT initialize(1197, 1); //# of controls (base + enhancements): 1196

    //Step 3: read all controls for each family
    db.DelayCommit(true);

    QFile file2(QStringLiteral(":/dod/src/800-53-rev5-controls.xml"));
    file2.open(QIODevice::ReadOnly);
    const QByteArray rmfControls = file2.readAll();
    file2.close();

    auto *xml = new QXmlStreamReader(rmfControls);
    QString control;
    QString family;
    QString title;
    QString description;
    bool inStatement = false;
    while (!xml->atEnd() && !xml->hasError())
    {
        xml->readNext();
        if (xml->isStartElement())
        {
            if (inStatement)
            {
                if (xml->name().compare(QStringLiteral("supplemental-guidance")) == 0)
                    inStatement = false;
                else if (xml->name().compare(QStringLiteral("description")) == 0)
                    description = xml->readElementText().trimmed();
                else if (xml->name().compare(QStringLiteral("family")) == 0)
                    family = xml->readElementText().trimmed();
                else if ((xml->name().compare(QStringLiteral("control")) == 0) || (xml->name().compare(QStringLiteral("control-enhancement")) == 0))
                {
                    inStatement = false;
                    Q_EMIT updateStatus("Adding " + control);
                    CheckFamily(control.left(2), family, familiesAdded, true);
                    db.AddControl(control, title, description);
                    Q_EMIT progress(-1);
                }
            }
            else
            {
                if (xml->name().compare(QStringLiteral("statement")) == 0)
                    inStatement = true;
                else if (xml->name().compare(QStringLiteral("number")) == 0)
                    control = xml->readElementText().trimmed();
                else if (xml->name().compare(QStringLiteral("title")) == 0)
                    title = xml->readElementText().trimmed();
                else if (xml->name().compare(QStringLiteral("description")) == 0)
                    description = xml->readElementText().trimmed();
                else if (xml->name().compare(QStringLiteral("family")) == 0)
                    family = xml->readElementText().trimmed();
                else if ((xml->name().compare(QStringLiteral("control")) == 0) || (xml->name().compare(QStringLiteral("control-enhancement")) == 0))
                {
                    Q_EMIT updateStatus("Adding " + control);
                    CheckFamily(control.left(2), family, familiesAdded, true);
                    db.AddControl(control, title, description);
                    Q_EMIT progress(-1);
                }
            }
        }
    }
    if (!control.isEmpty())
    {
        CheckFamily(control.left(2), family, familiesAdded, true);
        db.AddControl(control, title, description);
    }

    delete xml;

    //Step 4: prepare CCIs
    QFile file(QStringLiteral(":/dod/src/U_CCI_List.xml"));
    file.open(QIODevice::ReadOnly);
    const QByteArray xmlFile = file.readAll();
    file.close();

    //Step 5: Parse all CCIs
    Q_EMIT updateStatus(QStringLiteral("Parsing CCIs…"));
    QList<CCI> toAdd;
    xml = new QXmlStreamReader(xmlFile);
    QString cci = QString();
    QString definition = QString();
    while (!xml->atEnd() && !xml->hasError())
    {
        xml->readNext();
        if (xml->isStartElement())
        {
            if (xml->name().compare(QStringLiteral("cci_item")) == 0)
            {
                if (xml->attributes().hasAttribute(QStringLiteral("id")))
                {
                    for (const QXmlStreamAttribute &attr : xml->attributes())
                    {
                        if (attr.name().compare(QStringLiteral("id")) == 0)
                            cci = attr.value().toString();
                    }
                }
            }
            else if (xml->name().compare(QStringLiteral("definition")) == 0)
            {
                definition = xml->readElementText();
            }
            else if (xml->name().compare(QStringLiteral("reference")) == 0)
            {
                if (xml->attributes().hasAttribute(QStringLiteral("version")) && xml->attributes().hasAttribute(QStringLiteral("index")) && !cci.isEmpty())
                {
                    QString version = QString();
                    QString index = QString();
                    for (const QXmlStreamAttribute &attr : xml->attributes())
                    {
                        if (attr.name().compare(QStringLiteral("version")) == 0)
                            version = attr.value().toString();
                        else if (attr.name().compare(QStringLiteral("index")) == 0)
                            index = attr.value().toString();
                    }
                    if (!version.isEmpty() && !index.isEmpty() && (version == QStringLiteral("5"))) //Only Rev 5 (RMF) supported
                    {
                        int cciInt = QStringView{cci}.right(6).toString().toInt();
                        QString control2 = index;
                        int tmpIndex = index.indexOf(' ');
                        if (control2.contains(' '))
                            control2 = control2.left(control2.indexOf(' '));
                        if (control2.contains('.'))
                            control2 = control2.left(control2.indexOf('.'));
                        if (index.contains('('))
                        {
                            //check if a second space is present. If the parenthesis is after the second space, it is not an enhancement.
                            tmpIndex = index.indexOf(' ', tmpIndex + 1);
                            int tmpInt = index.indexOf('(');
                            if (tmpIndex <= 0 || tmpInt < tmpIndex)
                            {
                                QString enhancement(index);
                                enhancement = enhancement.remove(0, tmpInt);
                                enhancement = enhancement.left(index.indexOf(')') - tmpInt + 1);
                                control2.append(enhancement);
                            }
                        }
                        CCI c;
                        c.cci = cciInt;
                        c.controlId = db.GetControl(control2).id;
                        c.definition = definition;
                        toAdd.append(c);
                    }
                }
            }
        }
    }
    delete xml;

    //Step 6: add CCIs
    Q_EMIT initialize(toAdd.size() + 1, 1);
    db.DelayCommit(true);
    QList<CCI> inDB = db.GetCCIs().toList();
    for (const CCI &c : toAdd)
    {
        //check if the DB has this CCI already here for performance
        if (inDB.contains(c))
            continue;
        inDB.append(c);
        CCI tmpCCI = c;
        Q_EMIT updateStatus("Adding CCI-" + QString::number(c.cci) + "…");
        db.AddCCI(tmpCCI, false);
        Q_EMIT progress(-1);
    }
    db.DelayCommit(false);

    //complete
    Q_EMIT updateStatus(QStringLiteral("Done!"));
    Q_EMIT finished();
}
