name: Debian CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: set timezone
      run: sudo ln -fs /usr/share/zoneinfo/America/Chicago /etc/localtime
#    - name: install latex dependencies
#      run: DEBIAN_FRONTEND="noninteractive" sudo apt-get install -q -y --force-yes texlive-luatex texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-extra-links texlive-bibtex-extra biber
    - name: install dependencies
      run: DEBIAN_FRONTEND="noninteractive" sudo apt-get install -q -y --force-yes qt5-default libzip-dev cmake g++ debhelper dpkg-dev
    - name: download libxlsxwriter
      run: pushd /tmp && wget https://github.com/jmcnamara/libxlsxwriter/archive/RELEASE_1.0.6.tar.gz && tar -zxf RELEASE_1.0.6.tar.gz && popd
    - name: build libxlsxwriter
      run: pushd /tmp/libxlsxwriter-RELEASE_1.0.6 && echo -e "SET(CPACK_GENERATOR \"DEB\")\nset(CPACK_PACKAGE_NAME \"libxlsxwriter\")\nSET(CPACK_DEBIAN_PACKAGE_MAINTAINER \"jwh0011@auburn.edu\")\nset(CPACK_PACKAGE_VERSION \"1.0.6\")\nINCLUDE(CPack)" >> CMakeLists.txt && cmake ./ && make -j3 && cpack && popd
    - name: install libxlsxwriter
      run: sudo dpkg -i /tmp/libxlsxwriter-RELEASE_1.0.6/libxlsxwriter-1.0.6-Linux.deb
    - name: build tarball
      run: git archive --format=tar.gz -o ../stigqter_1.1.2.orig.tar.gz master
    - name: dpkg-buildpackage
      run: dpkg-buildpackage --no-sign
    - name: copy debian package
      run: mv ../stigqter_1.1.2-1_all.deb /tmp/
    - uses: actions/upload-artifact@v2
      with:
        name: STIGQter Debian Package
        path: /tmp/stigqter_1.1.2-1_all.deb
    - uses: actions/upload-artifact@v2
      with:
        name: libxlsxwriter Debian Package
        path: /tmp/libxlsxwriter-RELEASE_1.0.6/libxlsxwriter-1.0.6-Linux.deb
